[versions]
agp = "9.3.1"
coreKtx = "1.10.1"
dexkit = "2.2.0"
lifecycleRuntimeKtx = "2.6.1"
recyclerview = "1.4.0"
smaliDexlib2 = "3.0.9"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
smali-dexlib2 = { module = "com.android.tools.smali:smali-dexlib2", version.ref = "smaliDexlib2" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

