[versions]
agp = "9.3.1"
dexkit = "2.2.0"
smaliDexlib2 = "3.0.9"

[libraries]
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
smali-dexlib2 = { module = "com.android.tools.smali:smali-dexlib2", version.ref = "smaliDexlib2" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }